<?php

namespace App;

use App\Scope\ValidScope;
use Illuminate\Database\Eloquent\Model;

class Annonce extends Model
{
    protected $table = 'annonces';

    protected  $guarded = ['id'];

    public function category(){
        return $this->belongsTo(\App\Category::class);
    }

    public function user(){
        return $this->belongsTo(User::class, 'creator_user_id');
    }

    public function scopeValid($query)
    {
        return $query->where('is_valid', true);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //static::addGlobalScope(new ValidScope());
    }

}
